common/HighlightJs.bs.js
common/HighlightJs.re
components/Text.bs.js
components/Text.re
layouts/BeltDocsLayout.bs.js
layouts/BeltDocsLayout.re
package.json
pages/belt_docs/array.mdx
styles/_hljs.css
styles/main.css
yarn.lock

Adds syntax highlighting via highlight.js.
This uses the `hljs.highlight` function inside the `Text.Code` component, which will work perfectly fine with NextJS' SSR.
Also right now, all code fences without a language will be highlighted as `reason` code by default. We can change that as soon as every code fence has a tagged language, but for now I recommend handling it like this.

Syntax highlighting

---

pages/belt_docs/option.mdx

Hey all! Love all your work on this!!
I copied over everything from https://bucklescript.github.io/bucklescript/api/Belt_Option.html, and added a few examples.
Currently, I've added:
```
**Usage**
...
**Examples**
```
To all functions, it'd be nice if these could be anchor-links for easy sharing. But might be something for the future. 🙂
Let me know if there's anything that needs changing!
Closes #3

docs(belt): update Option-module docs

---

pages/belt_docs/hash-set.mdx
pages/belt_docs/map-dict.mdx
pages/belt_docs/map-int.mdx
pages/belt_docs/map-string.mdx
pages/belt_docs/mutable-set-int.mdx
pages/belt_docs/mutable-set-string.mdx
pages/belt_docs/mutable-set.mdx
pages/belt_docs/result.mdx
pages/belt_docs/set-dict.mdx
pages/belt_docs/set-int.mdx
pages/belt_docs/set-string.mdx
pages/belt_docs/set.mdx
pages/belt_docs/sort-array.mdx

Fixes `Set`, `Set.Int`, `Set.String`, `Set.Dict`, `MutableSet`, `MutableSet.Int`, `MutableSet.String`, `SortArray`, `HashSet`, `Map.Int`, `Map.String`, `Result` examples.
All tests are passing so I assume it resolves #29 and resolves #27.

belt-docs: fix all failing examples

---

pages/belt_docs/list.mdx

fix mapReverse2 example formatting

---

pages/belt_docs/set.mdx
scripts/test-belt-examples.js

This PR will enable prelude snippet support. What does that mean? Some modules require some shared code to express examples more easily (and to reduce repetitive writing). Such as the `pages/belt_docs/set.mdx` file.
How to use it?
Preferably in the beginning of the module description, you add your prelude as a codeblock with a `re prelude` metastring. This will still render the codeblock like any other example, but in the testing script, it will do following extra tasks:
- It will test all preludes before executing any examples (if a prelude doesn't work, all examples will fail anyways)
- If the preludes do work, the test script will find and concatenate all prelude codeblocks, and prepend them to each example code before execution
Also this PR fixes an issue with line number parsing / …

Add prelude support

---

pages/index.mdx

Just a couple small typo fixes to the index page I noticed as I was looking at the contributions section.

fix index page typos

---

pages/belt_docs/list.mdx

Fixes #50 
Adds examples for more Belt.List functions.
Do we want examples for the uncurried functions as well?

add more examples for Belt.List

---

layouts/BeltDocsLayout.bs.js
layouts/BeltDocsLayout.re

According to MDN, to make non-interactive elements (like `div`, `span` or `li`) tab-able, one needs to set `tabindex=0` on such an element.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets

Fix #67: Make sidebar items focusable in FF.

---

pages/apis/javascript/latest/belt.mdx
pages/apis/javascript/latest/js.mdx

(Also cleaned up/unified some minor things with the Belt introduction I wrote previously.)
I hope that the information regarding the Js.Xxx -> Js.Xxx2 migration is accurate, as I have not received any answer to my questions in https://github.com/BuckleScript/bucklescript/issues/2975#issuecomment-542549940.
@ryyppy In the JS docs, the style is currently somewhat broken as the headlines (h2) are invisible.

Introduction to the Js module, including information about data-first vs. data-last

---

components/Navigation.bs.js
components/Navigation.re
layouts/ManualDocsLayout.bs.js
layouts/ManualDocsLayout.re
layouts/ReasonCompilerDocsLayout.bs.js
layouts/ReasonCompilerDocsLayout.re
layouts/ReasonReactDocsLayout.bs.js
layouts/ReasonReactDocsLayout.re
pages/docs/manual/latest/extra-goodies.mdx
pages/docs/manual/latest/installation.mdx
pages/docs/manual/latest/introduction.mdx
pages/docs/reason-compiler/latest/comparison-to-jsoo.mdx
pages/docs/reason-compiler/latest/concepts-overview.mdx
pages/docs/reason-compiler/latest/introduction.mdx
pages/docs/reason-react/latest/installation.mdx
pages/docs/reason-react/latest/introduction.mdx

- Move /docs/manual/latest.mdx to /docs/manual/latest/introduction.mdx
- Same for reason-compiler and reason-react
- Make sure all links point to the new urls
- Makes the breadcrumbs show up on each introduction page

Fix some doc structure issues

---

layouts/ReasonCompilerDocsLayout.bs.js
layouts/ReasonCompilerDocsLayout.re
pages/docs/reason-compiler/latest/decorators.mdx
pages/docs/reason-compiler/latest/interop-cheatsheet.mdx

This solves #100. 
This PR is basically the whole bs-blabla as-is. I only added a small Intro and some Info-Boxes where applicable.
I also added two decorator sections which are not (yet) included in bs-blabla. At some point we need to revise the content anyway, because it does not take records-as-objects into account (and maybe more things).
Furthermore, the new [@unboxed] attribute would also fit in here, but it is not a `@bs.`-decorator.

Add bs-blabla to Reason JS Compiler docs.

---

pages/docs/manual/latest/function.mdx

The difference between the signature and the type annotations with functions with optional labeled arguments can be confusing.
I added a sub-part inside Optional Labeled Arguments because there were already 2 notes so I thought it would become too messy.
I'm not sure how to link to another page though.
I hope this can help!

Signature for optional arguments

---

pages/docs/manual/latest/function.mdx
pages/docs/manual/latest/imperative-loops.mdx

This adds some information to the Recursive Functions section to explain why we use them. It also adds a note at the end of the Imperative Loops section explaining how you can achieve an “early return” by using a recursive function.

Expanded information about recursive functions

---

pages/docs/manual/latest/interop.mdx

"" empty string has been deprecated in favour of explicitly stating the external function name

Remove text about deprecated empty string for the text of external

---

pages/apis/javascript/latest/belt.mdx
pages/apis/javascript/latest/belt/array.mdx
pages/docs/manual/latest/list-and-array.mdx

This adds a few paragraphs about how array access is handled by Belt. This seems to be a common source of confusion, and I haven’t seen it mentioned anywhere else in the docs.
I wasn’t sure where the best location for this would be, so I put it in the “implementation details” page.

Added information about array access type errors

---

README.md
package.json
postcss.config.js
tailwind.config.js
yarn.lock

- Fixes audit errors
- Upgrades to tailwind 1.4 with integrated purge-css support (streamlines purgecss configuration without the need to wiring it up ourselves in postcss.config.js)
- adds postcss-cli as a dev dependency to make the postcss command in the README is easier to run

Upgrade dependencies

---

components/Text.gen.js
pages/apis/javascript/latest/js/string-2.mdx
pages/apis/javascript/latest/js/string.mdx

* Added links to MDN for corresponding methods.
* Added deprecation notes for `array()` and `link()`
* Added legacy function note for `substr()`.
* Eliminated `Js.log()` in examples.

Add MDN references to String and String2.

---

_blogposts/compiler/a-story-of-exception-encoding.mdx

As seen on: https://bucklescript.github.io/blog/2020/05/06/exception-encoding

Add better-exception-encoding blog post

---

components/Meta.re

This makes it easier for RSS readers to find the RSS feed so that people
that want to subscribe can just add reasonml.org to their RSS reader.

Add meta link to RSS feed

---

_blogposts/compiler/a-story-of-lazy-encoding.mdx
layouts/ManualDocsLayout.re
layouts/ReasonCompilerDocsLayout.re
pages/docs/manual/latest/lazy-values.mdx

- Remove runtime representation part
- Add notes header
- Refine Function wrapping section

Move lazy-values section to Reason manual

---

pages/docs/manual/latest/introduction.mdx

Fixed the typo and wording in documentation text of introduction page in the **Reason isn't for you?** section.

Fixed the typographical error in introduction page
