- pages/belt_docs/hash-map-int.mdx
- pages/belt_docs/hash-map-string.mdx
- pages/belt_docs/hash-map.mdx
- pages/belt_docs/hash-set.mdx
Not much there in the original docs, but soon we at least match the original docs and can recommend it to users.
> Hashmap docs

- common/Util.bs.js
- common/Util.re
- components/CodeExample.bs.js
- pages/belt_docs/set-dict.mdx
- pages/belt_docs/set-int.mdx
- pages/belt_docs/set-string.mdx
- pages/belt_docs/set.mdx
> Add Set, Set.Int, Set.String, Set.Dict docs

- pages/belt_docs/mutable-set-int.mdx
- pages/belt_docs/mutable-set-string.mdx
- pages/belt_docs/mutable-set.mdx
- pages/belt_docs/set-dict.mdx
- pages/belt_docs/set-int.mdx
- pages/belt_docs/set-string.mdx
- pages/belt_docs/set.mdx
Resolves #24 + few improvements to `Belt.Set` docs
> Belt.MutableSet, Belt.MutableSet.String, Belt.MutableSet.Int docs

- bindings/Next.re
- common/Util.bs.js
- common/Util.re
- layouts/BeltDocsLayout.bs.js
- layouts/BeltDocsLayout.re
- package.json
- scripts/extract-belt-index.js
- scripts/test-belt-examples.js
Adds navigation for module content.
**Preview:**
> Add function toc

- components/CodeSignature.bs.js
- components/CodeSignature.re
- layouts/MainLayout.re
- pages/belt_docs/map-dict.mdx
- pages/belt_docs/map-int.mdx
- pages/belt_docs/map-string.mdx
- pages/belt_docs/map.mdx
see https://github.com/reason-association/reasonml.org/issues/36#issuecomment-538132221
> Transfer MapInt, MapString, MapDict Docs

- components/CodeSignature.bs.js
- components/CodeSignature.re
- layouts/MainLayout.re
```
Warning number 26
/Users/anthonymittaz/Projects/Reason/reasonml.org/components/CodeSignature.re 2:14-21
1 │ [@react.component]
2 │ let make = (~children) => {
3 │   <div></div>
4 │ };
unused variable children.
[34/36] Building layouts/MainLayout.cmj
Warning number 33
/Users/anthonymittaz/Projects/Reason/reasonml.org/layouts/MainLayout.re 5:1-9
3 │
4 │ open Util.ReactStuff;
5 │ open Text;
6 │ module Link = Next.Link;
7 │
unused open Text.
[36/36] Building layouts/BeltProseLayout.cmj
```
> Suppress all the warnings when compiling bs for the first time

- layouts/BeltDocsLayout.bs.js
- layouts/BeltDocsLayout.re
> [Closes #14] Adds bs-platform version to docs header.

- pages/belt_docs/range.mdx
Closes #69. As I was going through this, I was just curious if there is some standard or minimal amount of requirements that each example should meet. If so, let me know! If not, it may be helpful to have a conversation around this for the sake of clarifying expectations.
> [Closes #69] Create Examples for Range

- pages/belt_docs/float.mdx
- pages/belt_docs/int.mdx
> Belt int and belt float examples

- pages/belt_docs.mdx
When I read the intro
> A stdlib shipped with BuckleScript This stdlib is still in beta but we encourage you to try it out and give us feedback.
I felt the urge to rewrite this page. 😉
> Rewrite Belt intro.

- pages/apis/javascript/latest/belt/hash-map-int.mdx
- pages/apis/javascript/latest/belt/hash-map-string.mdx
- pages/apis/javascript/latest/belt/hash-map.mdx
- yarn.lock
This PR adds examples (resolve #52 ) to following modules.
> Belt.HashMap examples

- components/Markdown.bs.js
- components/Markdown.re
- pages/docs/manual/latest/syntax-cheatsheet.mdx
- pages/docs/reason-compiler/latest/introduction.mdx
- scripts/test-hrefs.js
Fixes the href problem in #105
> Fix anchored href rendering

- components/Navigation.bs.js
- components/Navigation.re
> Make collapsible nav's mouse events work on iOS12 safari

- pages/docs/manual/latest/let-binding.mdx
- pages/docs/manual/latest/type.mdx
Syncs reasonml docs up to following commit:
https://github.com/reasonml/reasonml.github.io/commit/da986cb70cfeea3a6b4f5d3007f67d886d447efb
> Sync reason docs

- pages/apis/javascript/latest/js/option.mdx
Add descriptions and examples for functions in `Js.Option`
> Add documentation for Option in Js.

- pages/docs/manual/latest/variant.mdx
One more try at doing a commit that only contains the one changed file.
> Documentation for variants with records.

- pages/community/events.mdx
A small change to add the Twitter account of the Stockholm meetup group
> Add ReasonSTHLM Twitter

- pages/docs/reason-compiler/latest/decorators.mdx
Added some content to the missing bs.meth and bs.inline as well as updated the remaining content to mention the existence of the wonderful records-as-objects.
> Decorators revision

- pages/apis/javascript/latest/js/array.mdx
Includes links to relevant pages at MDN.
> Document Js.Array module.

- pages/apis/javascript/latest/js/array-2.mdx
Similar to documentation for `Js.Array`.
> Documentation for Js.Array2.

- _blogposts/ecosystem/reason-react-0-8-0.mdx
- index_data/blog_authors.json
There was also a formatting issue in the authors file. I guess that was not deliberately.
> Add ReasonReact 0.8.0 release blogpost.

- pages/docs/manual/latest/string-and-char.mdx
I'm a total newbie but I guess this is what was meant?
> Fix link to standard library for String

- layouts/ManualDocsLayout.re
- layouts/ReasonCompilerDocsLayout.re
- pages/docs/manual/latest/reserved-keywords.mdx
- pages/docs/reason-compiler/latest/handling-js-naming-collisions.mdx
Taking over the work done in #163
> Name mangling and keywords

- _blogposts/compiler/a-story-of-lazy-encoding.mdx
reference https://github.com/BuckleScript/bucklescript.github.io/pull/211
> new post about lazy encoding

- pages/docs/manual/latest/let-binding.mdx
> Fix Let Binding Example

- pages/community/events.mdx
Hi :wave: 
I'm starting to organize a new Reason meetup in Seoul, South Korea. I wanna add info about it here :)
> Add ReasonSeoul meetup & twitter

- _blogposts/compiler/a-note-on-bucklescripts-future-commitments.mdx
- common/BlogFrontmatter.re
- pages/blogpost-guide.mdx
- re_pages/Blog_Article.re
Adds a co-authors field for the blog frontmatter
Example render:
> Blog multiple authors

- pages/docs/reason-compiler/latest/new-project.mdx
Added `npm install` in the compile and run section of the new project page.
> Added command form dependency installation in new projects

- pages/docs/reason-compiler/latest/concepts-overview.mdx
fix https://github.com/BuckleScript/bucklescript/issues/4468
> update opam instructions for ocaml developers
